### PR TITLE
Add use case

### PR DESCRIPTION
**Pull request by rouson**
I am (hopefully) finally done refactoring the use-case scripts and will get back to incorporating bootstrap.sh into the OpenCoarrays installation scripts.

### CODE REVIEW

**Comment by zbeekman** [comment]
hmm please don't merge this PR something :fish:-y is going on I'll try to look into it soon

**Comment by rouson** [comment]
Possibly the transcript below is helpful.  In each execution of the script, I get the result I expect.  Are you trying something different and/or getting different results?

```bash
rouson@localhost:~$ cp ~/Code/bash3boilerplate/src/use-case/my-script.sh ./foo.sh
rouson@localhost:~$ cp ~/Code/bash3boilerplate/src/use-case/my-script.sh-usage ./foo.sh-usage
rouson@localhost:~$ ./foo.sh 
Please set B3B_USE_CASE to the bash3boilerplate use-case directory path.
rouson@localhost:~$ export B3B_USE_CASE=~/Code/bash3boilerplate/src/use-case/
rouson@localhost:~$ echo "${B3B_USE_CASE}"
/Users/rouson/Code/bash3boilerplate/src/use-case/
rouson@localhost:~$ ./foo.sh 

 Setting a file name with -f or --file is required

  -f --file [arg]  Filename to process. Required.
  -t --temp [arg]  Location of tempfile. Default="/tmp/bar"
  -V               Enable verbose mode, print script as it is executed
  -v --version     Print version number
  -d --debug       Enables debug mode
  -h --help        This page
  -n --no-color    Disable color output
  -1 --one         Do just one thing

2016-03-24 23:45:19 UTC [     info] Cleaning up. Done
rouson@localhost:~$ ./foo.sh -f
./foo.sh: option requires an argument -- f

 Invalid use of script: -f 

  -f --file [arg]  Filename to process. Required.
  -t --temp [arg]  Location of tempfile. Default="/tmp/bar"
  -V               Enable verbose mode, print script as it is executed
  -v --version     Print version number
  -d --debug       Enables debug mode
  -h --help        This page
  -n --no-color    Disable color output
  -1 --one         Do just one thing

rouson@localhost:~$ ./foo.sh -f bar
2016-03-24 23:45:31 UTC [     info] __file: /Users/rouson/foo.sh
2016-03-24 23:45:31 UTC [     info] __dir: /Users/rouson
2016-03-24 23:45:31 UTC [     info] __base: foo
2016-03-24 23:45:31 UTC [     info] __os: OSX
2016-03-24 23:45:31 UTC [     info] __usage: /Users/rouson/foo.sh-usage
2016-03-24 23:45:31 UTC [     info] LOG_LEVEL: 6
2016-03-24 23:45:31 UTC [     info] arg_f: bar
2016-03-24 23:45:31 UTC [     info] arg_d: 0
2016-03-24 23:45:31 UTC [     info] arg_v: 0
2016-03-24 23:45:31 UTC [     info] arg_V: 0
2016-03-24 23:45:31 UTC [     info] arg_h: 0
2016-03-24 23:45:31 UTC [     info] Cleaning up. Done
```

**Comment by rouson** [comment]
Never mind. I realize now that you were probably reacting to the history of 93 commits to merge.  I think at some point, I inadvertently merged [kvzh/bash3boilerplate](https://github.com/kvz/bash3boilerplate) into [zbeekman/bash3boilerplate](https://github.com/zbeekman/bash3boilerplate) and/or the reverse.  I'm pretty sure the scripts themselves are working as I expect so I'll proceed to use them in OpenCoarrays as soon as I have time to work on OpenCoarrays, which might be a few days away.

**Comment by zbeekman** [comment]
OK... I'll compare and try to fish out the extra commits

**Comment by zbeekman** [comment]
I'm closing the PR for now... I'll reopen later

**Pull request closed without merging**
